version: '3'
services:
  app:
    build: ./docker/php
    container_name: TourHunter_app
    volumes:
      - ./:/var/www
    depends_on:
      - TourHunter_db
  nginx:
    image: nginx:1.17
    container_name: TourHunter_nginx
    ports:
      - 8011:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/tour-hunter.com.conf:/etc/nginx/conf.d/tour-hunter.com.conf
    depends_on:
      - app
  TourHunter_db:
    image: mysql
    ports:
      - 3307:3306
    container_name: TourHunter_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: TourHunter_db
      MYSQL_USER: TourHunter_user
      MYSQL_PASSWORD: TourHunter_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

#Сборка docker-compose